### ISSUE TITLE
Your solution for Chapter 5, Exercise 1 is not correct.

### ISSUE THREAD

**Issue by AndreiVettor** [gleesik/The-C-Programming-Language-2nd-Edition-Solutions#1]
The buffer at the end of runtime doesn't contain the right values. For example if I input "-;" the buffer will contain ";;" instead of ";-".

**Comment by gleesik** [comment]
I will **fix** it. 👍

**Comment by gleesik** [comment]
The problem is fixed. Thank you! 🥇
