### ISSUE TITLE
Incomplete solution for 1.12

### ISSUE THREAD

**Issue by kotoffski** [gleesik/the-c-programming-language-2nd-edition-solutions#11]
The current solution for exercise 1.12 seems to not handle the case, where a couple of spaces and tabs goes one by one. It will currently print a new line for each space or tab.
Something like that would work in such case:

```
#include <stdio.h>

#define OUT 0
#define IN 1

int main(void)
{
  char c;
  int state;

  state = OUT;
  while ((c = getchar()) != EOF)
  {
    if (c != ' ' && c != '\t' && c != '\n')
    {
      putchar(c);
      state = IN;
    }
    else if (state)
    {
      putchar('\n');
      state = OUT;
    }
  }
  
  return 0;
}
```

**Comment by gleesik** [comment]
@kotoffski Interesting observation 😎. Can you make a **pull request** with your solution? Maybe it will help if you would explain your solution so that we can make it even more simple if possible or explore other alternatives.
