### ISSUE TITLE
Your solution for Chapter 1, Exercise 12 is redundant

### ISSUE THREAD

**Issue by aweebit** [gleesik/The-C-Programming-Language-2nd-Edition-Solutions#2]
Your [solution](https://github.com/gleesik/The-C-Programming-Language-2nd-Edition-Solutions/blob/8c2f6a3c5c6b12d87c9a493db3f0a80127b6eb9f/Chapter_01/Exercise_1_12/copy_io_nl.c) for 1-12 seems to be redundant. Why not just do it this way?

````c
#include <stdio.h>

#define OUT 0
#define IN 1

main() {
    int state = OUT;

    int c;
    while ((c = getchar()) != EOF) {
        if (c != ' ' && c != '\n' && c != '\t') {
            state = IN;
            putchar(c);
        } else if (state == IN) {
            state = OUT;
            putchar('\n');
        }
    }
}
````

Please correct me if I am wrong.

**Comment by gleesik** [comment]
I think that my approach is a little more expandable. It can be readapted if there is the need. Of course for the purpose of the exercise your solution is more simple.

I think that generally if every text line is processed individually the approach seems more natural, at least for me.

The performance however is pretty much the same, but the logic is more abstracted.

Does this make any sense? What is your opinion?

**Comment by aweebit** [comment]
I can't agree that my code is less expandable. For instance, it can just as easily be combined with the word counting example from the same chapter:

````c
#include <stdio.h>

#define IN 1
#define OUT 0

main() {
    int c, nl, nw, nc, state;

    state = OUT;
    nl = nw = nc = 0;

    while ((c = getchar()) != EOF) {
        ++nc;
        if (c != ' ' && c != '\n' && c != '\t') {
            if (state == OUT) {
                ++nw;
                state = IN;
            }
            putchar(c);
        } else {
            if (c == '\n')
                ++nl;
            if (state == IN) {
                state = OUT;
                putchar('\n');
            }
        }
    }

    printf("%d %d %d\n", nl, nw, nc);
}
````

The `newline` variable is completely unnecessary. It will always be `TRUE` when the `state` is `OUT`, and vice versa. Always, except the very first iteration of your program, because you initialize `state` to `OUT` and `newline` to `FALSE`. And here actually comes another problem with your code. If the stream begins with a whitespace character, an unnecessary newline will be output before actual words.

**Comment by gleesik** [comment]
I did some research, you are right. Can you make a pull request, but with my style of formating?

**Comment by aweebit** [comment]
Sure. #3
